environment:
  global:
    TARGET: x86_64-pc-windows-msvc
    BITS: 64
    RUST_VERSION: stable
    CRATE_NAME: aget-rs
    CARGO_HOME: "c:\\cargo"
    RUSTUP_HOME: "c:\\rustup"
    VCPKG_DEFAULT_TRIPLET: x64-windows
    VCPKGRS_DYNAMIC: 1

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\cargo\bin
  - rustc -Vv
  - cargo -V
  - git clone https://github.com/Microsoft/vcpkg c:\projects\vcpkg
  - c:\projects\vcpkg\bootstrap-vcpkg.bat
  - set VCPKG_ROOT=c:\projects\vcpkg
  - echo yes > %VCPKG_ROOT%\Downloads\AlwaysAllowDownloads
  - if defined VCPKG_DEFAULT_TRIPLET %VCPKG_ROOT%\vcpkg.exe install openssl

build: false

test_script:
  - cargo test --target %TARGET% --verbose
  - cargo run --target %TARGET% -- "http://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg"
  - ps: Remove-Item –path .\googlechrome.dmg

before_deploy:
  # Generate artifacts for release
  - cargo build --release --verbose
  - ps: ci\before_deploy.ps1

deploy:
  description: 'Automatically deployed release'
  artifact: /.*\.zip/
  # Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Then go to 'https://ci.appveyor.com/tools/encrypt' and enter the newly generated token.
  # - Enter the "encrypted value" below
  auth_token:
    secure: wXCkb6BE84VQOXhGKSRtANViz8PYnptF8K5HKJlsetkUpVllaHDh47B49FBiwj/v
  provider: GitHub
  on:
    RUST_VERSION: stable
    appveyor_repo_tag: true

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
